### ISSUE TITLE
Current liquidation mechanism is ineffective and dangerous

### ISSUE THREAD

**Issue by zobront** [DyadStablecoin/contracts-v3#15]
### Summary

The liquidation mechanism is intended to keep the protocol overcollateralized. However, the current mechanism design seems inherently unstable and doesn't accomplish the objective.

Currently, the logic for liquidation is as follows:
- The shares held by a specific dNFT falls below a certain threshold (currently 0.1%)
- A Liquidator sends sufficient ETH to push that dNFT's shares above the threshold
- The Liquidator gets possession of the dNFT, as well as all the shares that it previously owned

There are a number of issues I see with this. I'll go into details below, and then share some thoughts on how this might look in the Recommendations section.

#### No Stable Equilibrium

There is no game theoretically stable place for this system to land. The specifics will depend on the threshold that is chosen, but at most thresholds there will always be users who are near the line (at some, like the current 0.1%, it is a mathematical guarantee that at least half of the users will be liquidatable at all times).

This creates a competitive dynamic that users will always need to be fighting to be in the top 50%, liquidating other users, and depositing ETH in to stay near the top.

While this is reminiscent of some of the most fun degen projects of 2022, the goal for core is to provide stability, and these dynamics are not conducive to such stability.

#### Not Fair to Users Who Get Liquidated

Even in the even that we want these competitive dynamics, there are a spectrum of possibilities between favoring the user who is liquidated or who is the liquidator.

This system heavily favors the liquidator, in a way that feels unfair to normal users.

If a user's number of shares falls even 1% shy of the threshold, a liquidator can add that 1% and take the original user's 99%, as well as their dNFT. A more reasonable system might require the liquidator to put up the full 100%, and refund the original user their 99%, losing them their dNFT only.

#### Doesn't Accomplish the Stated Goal

We need to use liquidations as a tool to keep the system overcollateralized. This means, as much as possible, we should (a) understand the situations that might cause undercollateralization and allow liquidations to resolve this issue, and (b) not have liquidations impact behavior when they don't support this goal.

Looking at a few examples, we can see that the current example is off:
- A user with 1% of the dD but 20% of the withdrawn DYAD is contributing massively to missing the collateralization ratio, but would not be liquidatable
- A user with 0.01% of the dD and no withdrawn DYAD is not negatively impacting the collateralization ratio, but would be liquidatable

#### Easily Abusable

Since users who might be performing the liquidations also have the ability to impact the `totalDeposits` (which is the denominator in calculating the liquidation threshold), it's easy for a user to put the contract in a state that allows liquidations that wouldn't otherwise be possible.

This is similar to the issue discussed in #4.

### Recommendations

If our goals are to have liquidations keep the protocol overcollateralized, the simplest way to accomplish this is to force every dNFT to be similarly overcollateralized.

This also has the advantage of keeping liquidations based on a user's own decisions, rather than outside circumstances that can be manipulated by other users.

Furthermore, enforcing collateralization on the user level avoids the unfair situation that is currently possible, where one user gets more "benefit" in the form of withdrawing DYAD than another, because the first user withdraws first, and the second is therefore unable to because of the system-wide collateralization ratio.

This is difficult to accomplish, especially in the current system where the ideal invariant of `totalDeposit * ETH price == address(this).balance` is not enforced. However, if changes are made to the rebasing process to ensure that this becomes a true invariant, it opens up the ability to track this properly.

One way to accomplish this would be:
- We can create a `_shares2Deposit()` function that calculates the underlying DYAD value of a number of shares
- We can add a `mapping (uint => uint) dyadWithdrawn` that tracks the DYAD that's been withdrawn for each dNFT
- When redeeming (ETH) or withdrawing (DYAD), we can check the user invariant that, after the changes are made, `_shares2Deposit(id2Shares[id]).divWadDown(dyadWithdrawn[id]) >= MIN_COLLATERIZATION_RATIO`.
- There could still be a situation where a user falls below the `MIN_COLLATERIZATION_RATIO` based on the price of ETH falling. In this case, they would be susceptible to a gentle liquidation to incentivize a third party to bring the dNFT back into the correct range (ie the user would have their ETH refunded and the liquidator would supply the replacement ETH, and would get the dNFT as a reward).

I'm happy to brainstorm regarding other options, but this seems to be to be the most elegant way to use liquidations effectively to make the system stable, safe, and fair.

**Comment by SharifElfouly** [comment]
@zobront how I think a dNFT specific CR liquidation mechanism could work https://github.com/DyadStablecoin/contracts-v3/pull/20

**Comment by zobront** [comment]
@SharifElfouly Ok, I've gone through this. It looks good. I just have a few questions:

1) We let users withdraw or redeem to get themselves into liquidatable territory. Ideally we should avoid that, right? We want to keep liquidations to only when ETH price movement pushes them liquidatable. I'd add a similar check that stops them from redeeming or withdrawing if they fall below collateralization ratio.

2) It's still such that the liquidator is just expected to add the difference to be properly collateralized, and then they steal all the DYAD attached to the NFT with it. Is that what you want? Seems more fair to me that the liquidator would get just the NFT (and maybe some share of the underlying) but not the whole thing.

3) I don't think you should allow redeeming without attaching it to a `from`. I know it might seem weird for some users who just buy it, but then the system can get out of whack where more DYAD is withdrawn than is actually in circulation, and it'll always think it's not sufficiently collateralized. UI can have "pick a random person to support" or something to make it easy if they don't know.

4) I noticed we don't have a way to "unwithdraw" (ie move DYAD back to dD). Should we have that? Seems like it may be useful to fix collateralization issues, rather than needing to redeem and redeposit.

**Comment by SharifElfouly** [comment]
1) We want to keep away from someone to "quit" the game. so they should be able to redeem their whole deposit and move on.
2) I would keep it as it is. that way the incentive is even higher to avoid liquidations.
3) hmm feels kind of weird to have a from here... but yeah you are right about the circulation issue. In v2 we had it so only dNFT holders can redeem DYAD maybe we go back to that?
4) I wanted to do it through a multi-call. feels a bit redundant for me to have a dedicated function for it

**Comment by zobront** [comment]
1. We want to keep away from someone to "quit" the game. so they should be able to redeem their whole deposit and move on.

This should still be possible. As long as someone has no outstanding DYAD, they can redeem their whole deposit. You just need a special check in there that if id2Withdrawn[id] == 0, all redeeming is ok (to avoid `divWadDown` from reverting on the check).

2. I would keep it as it is. that way the incentive is even higher to avoid liquidations.

Cool, makes sense.

3. hmm feels kind of weird to have a from here... but yeah you are right about the circulation issue. In v2 we had it so only dNFT holders can redeem DYAD maybe we go back to that?

I like that better.

4. I wanted to do it through a multi-call. feels a bit redundant for me to have a dedicated function for it. 

Up to you! Not critical to system working but seems like a missing piece when every other interaction ETH <=> dD <=> DYAD is covered.

**Comment by SharifElfouly** [comment]
1. ok, perfect
3. lets check if joey
4. you are right. lets put it back in

**Comment by SharifElfouly** [comment]
PR to add function to deposit DYAD directly https://github.com/DyadStablecoin/contracts-v3/pull/23

**Comment by zobront** [comment]
> PR to add function to deposit DYAD directly #23

Looks great. I see that in #20 this function also has the `id2Withdrawn` update in it. With that in there, looks great to me.
