### ISSUE TITLE
Use SafeMint when minting new dNFTs

### ISSUE THREAD

**Issue by zobront** [DyadStablecoin/contracts-v3#16]
### Summary

Both `mint()` functions to mint new dNFTs have a `to` field to input who will receive the NFT. This can be dangerous in the event that a user specifies a contract address that is not set up to handle NFTs, and the dNFT gets stuck.

This is harmful to the user, but also to the protocol. There are a limited number of dNFTs, and there's an expectation that they will be used to provide liquidity and add to the circulating supply of DYAD. Locked dNFTs are a drag on the system.

While the current liquidation system would give the ability to take the NFTs from these inactive accounts, the proposed new liquidation system (see #15) does not, so it is important that we do what we can to protect against these errors.

### Recommendations

Use the `_safeMint()` function (already included in the imported OpenZeppelin ERC721 contract) instead of `_mint()`.

**Comment by SharifElfouly** [comment]
fixed by https://github.com/DyadStablecoin/contracts-v3/pull/18/files

**Comment by zobront** [comment]
Fix confirmed in #18.
